#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5
# bspc monitor HDMI-1-0 -d 6 7 8 9

wmname LG3D

bspc config focused_border_color "#ce6f8f"

# mouse
bspc config pointer_modifier		mod4
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	false
bspc config pointer_motion_interval	5


bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a feh state=floating

# Compositor
picom --experimental-backend &

# Wallpaper
feh --bg-fill ~/.local/wallpapers/spaceduck.png &

~/.config/polybar/launch.sh &
wired &
